class AppConstants {
  const AppConstants._();

  static const appName = 'TimeTrack Pro';
  static const version = '0.9.6';
  static const buildNumber = '2';
  static const betaName = 'Founder Beta';
  static const creatorName = 'Ponrat Saripan';
  static const productFamily = 'Business OS';
  static const channel = 'Founder Beta';
  static const buildLabel = 'Sprint 003 Production Readiness Beta';
  static const gitCommit = String.fromEnvironment(
    'GIT_COMMIT',
    defaultValue: 'development',
  );
  static const copyright = '© 2026 Ponrat Saripan. All rights reserved.';
  static const shortCopyright = '© 2026 Ponrat Saripan';
  static const generatedByTitle = 'Generated by TimeTrack Pro';
  static const generatedByFooter =
      'Generated by TimeTrack Pro\n© 2026 Ponrat Saripan. All rights reserved.';
  static const tagline = 'บันทึกเวลา คำนวณ OT สรุปรายได้ ส่งรายงาน HR';
  static const databaseName = 'timetrack_pro';
}
