class AppConstants {
  const AppConstants._();

  static const appName = 'TimeTrack Pro';
  static const version = '0.9.0';
  static const buildNumber = '1';
  static const betaName = 'Founder Beta';
  static const creatorName = 'Ponrat Saripan';
  static const productFamily = 'Business OS';
  static const copyright = '© 2026 Ponrat Saripan. All rights reserved.';
  static const generatedByFooter =
      'Generated by TimeTrack Pro — © 2026 Ponrat Saripan';
  static const tagline = 'บันทึกเวลา คำนวณ OT สรุปรายได้ ส่งรายงาน HR';
  static const databaseName = 'timetrack_pro';
}
